### ISSUE TITLE
Pokemon Sapphire intro rendering

### ISSUE THREAD

**Issue by alyosha-tas** [alyosha-tas/GBAHawk#11]
One of the 5 water ripples is partially cut off.

There isn't enough time to render  5 x 64 width affine and double sized sprites (that would take at minimum 128 * 2 * 5 = 1280 cycles and only 1232 exist in a scanline.) And this not even counting OAM fetch times.

I've double checked my rendering code and it matches up with current knowledge, nothing seems amiss.

Somehow it works on console though, so maybe some pixels out of range in the x direction don't get fetched? Time has to be saved somewhere.

**Comment by fleroviux** [comment]
I had this same issue at one point. Sprites are indeed horizontally clipped. That is all the sprite pixels which are out-of-bounds on the left side of the screen are skipped. I hadn't gotten around to document this yet (most of my documentation was written before I set out to do a final implementation of cycle PPU), so there definitely are some not documented yet things.

**Comment by alyosha-tas** [comment]
Ah ok, that makes sense, thanks for verifying, shouldn't be too hard to implement then.
