### ISSUE TITLE
[Request] 2 Players GBA Mode.

### ISSUE THREAD

**Issue by xRavenXP** [alyosha-tas/GBAHawk#14]
Does this emulator support Tool Assisted with 2 players on GBA? If yes, let me know. If not, please put this mode.

**Comment by alyosha-tas** [comment]
It has experimental support, use tools->multi-disk bundler.

I haven't tested a lot for 2 players, what games specifically are you interested in?

**Comment by xRavenXP** [comment]
Contra Advance, Turok Evolution, Double Dragon Advance, Advance Guardian Heroes, Disney’s Magical Quest (1, 2 and 3)... There are many amazing games on the GBA!

**Comment by alyosha-tas** [comment]
Linking seems pretty stable in v1.7. Please try that version and make bug reports for specific games if you encounter them.
