### ISSUE TITLE
Movies should internally contain GBAHawk version

### ISSUE THREAD

**Issue by RetroEdit** [alyosha-tas/GBAHawk#19]
This is something unfortunate I realized recently. While at least 9 different versions of GBAHawk have been released, all of them insert the same `emuVersion Version 1.0.0` and `OriginalEmuVersion Version 1.0.0` in the movie's `Header.txt`. It would be nice if future versions properly maintained the version number.

I also noticed that movies made in previous GBAHawk versions sometimes cause newer versions to abort movie loading because of incompatible sync settings. Maintaining compatibility here might be something to consider, but I do understand GBAHawk has been relatively fluid in its development, and having to support previous movie versions may add excessive maintenance burden for relatively little payoff.

**Comment by alyosha-tas** [comment]
Updated version to 2.0.0 for when I finally figure out the last bits needed for console verification of Metroid Fusion.

I'm not too worried about older movies, as there are so few movies and older versions will be obsolete, and sync settings should be more stable now.

**Comment by RetroEdit** [comment]
This is unfortunately again an issue with 2.0.3, where movies made in it will be labeled as 2.0.2 movies. My recommendation is to copy BizHawk's workflow and update the version string immediately after each version update -- this has the extra benefit that dev versions will have the expected version string. Of course, sometimes, you won't know if the next version will be a patch or minor update, but it can be always be updated further later.

And/or maybe even a release checklist of things to do before releases?

I realize this may seem like sort of a minor nitpicky issue, but it does make it a bit more difficult to keep track of local file movie versions and potentially necessary context if a GBAHawk movie is submitted to TASVideos. (Although to be fair, my local solution of including the movie version in the file name has been working well enough).
