### ISSUE TITLE
"2: Save Failed." in Mario Pinball Land

### ISSUE THREAD

**Issue by CloakTheLurker** [alyosha-tas/GBAHawk#21]
On GBAHawk 2.0.0, this error screen shows up, and the game doesn't save to RAM.
![save-error](https://github.com/alyosha-tas/GBAHawk/assets/143768607/64c9a1d9-8de9-408a-ad10-4f834156c83e)

**Comment by alyosha-tas** [comment]
Thanks for the report, fixed in master. (Was using the wrong size EEPROM)
