### ISSUE TITLE
DK: King of Swing: crash in Treacherous Twister

### ISSUE THREAD

**Issue by RetroEdit** [alyosha-tas/GBAHawk#22]
The game crashes in Treacherous Twister. This sounds like a bug mGBA also had a few years back: https://github.com/mgba-emu/mgba/issues/457

I was using GBAHawk 2.0.0, so maybe this has been fixed now? But none of the recent commits look like they address this. I'll probably pull it down and build it for future resyncs.

I will note that DK: King of Swing is generally a very stable game timing-wise. I wouldn't be surprised if the original mGBA movie is able to sync on real console (possibly with one or two frame adjustments at the very beginning).

## Repro
[TreachorousTwister_Crash.zip](https://github.com/alyosha-tas/GBAHawk/files/12795736/TreachorousTwister_Crash.zip)
Save file + movie that reaches the save file.

**Comment by alyosha-tas** [comment]
Yup I did in fact manage to miss the fact that some of the upper bits WAITCNT are read only (despite it specifically saying so in GBA Tek.)

Thanks for the report and link to the fix, fixed in master.
