### ISSUE TITLE
No Ffmpeg Writer

### ISSUE THREAD

**Issue by gabraltar** [alyosha-tas/GBAHawk#23]
A notable issue I am having with gbahawk atm is that there's no option for ffmpeg writer, like there is in bizhawk. The only other options for recording splits the recording into several different clips, and from what I can tell, it ends up skipping some parts of the recording. There isn't really much of another option to record.

**Comment by alyosha-tas** [comment]
Originally I just stripped down as much as I thought reasonable to minimize the maintenance burden, but it seems people like ffmpeg so I'll add it back in when I get a chance.

I've never had any skipping issues though, and I never touched the avi code so it should be the same as BizHawk. If you have any repro. steps please report them.

**Comment by gabraltar** [comment]
uh, I could be wrong on the skipping part, or was just using a bad writer method. I'll check when I have time

If it doesn't lose video, then no ffmpeg writer isn't a _huge_ deal, I can just put together the split videos. It would still be appreciated if you have the time/motivation to do it tho.

**Comment by gabraltar** [comment]
just check and yeah I lied, splitting the video does not lose video

sorry about that. since that's not the case, ffmpeg writer isn't super necessary, it would just be nice for convinence

**Comment by alyosha-tas** [comment]
done in 2.0.3
