### ISSUE TITLE
'Power' button doesn't work in multi-GBA situations

### ISSUE THREAD

**Issue by RetroEdit** [alyosha-tas/GBAHawk#26]
With multiple GBAs open, I tried both of the power buttons in virtual pad and nothing happened. I also tried binding it to the controller and creating a TAStudio movie.

I'm used the multi-disk bundler to load up Game & Watch Gallery 4 along with the BIOS (since it's a game with Single-PAK multiplayer game).

**Comment by alyosha-tas** [comment]
Proper power cycling in linked mode actually isn't supported currently, I would need full subframe support first since the frames would no longer line up after power cycle.

Do you have a particular use case in mind?

**Comment by RetroEdit** [comment]
In this case, if I were to do a full completion Game & Watch Gallery 4 TAS, I believe I would need to power-cycle the dependent GBA multiple times to initiate new link transfers when playing different subgames.

**Comment by RetroEdit** [comment]
Yes, that would technically work, but it's not ideal, since it's a faster TAS if you never power-cycle the primary GBA.

To me, I don't understand how they can line-up on the first simultaneous power-cycle, but power-cycling the second GBA would introduce additional complexity. Is it just a matter of added subframe support to line the second GBA up a single time when it power-cycles, or would the changes have to be more involved than that? Or am I not understanding what subframe support means in this context?

(Side note: in my niche situation, I probably don't need the second GBA to press any inputs, just to turn on. But that detail probably shouldn't affect implementation).

Just to be clear -- this isn't high priority for me, since a full Game & Watch Gallery 4 TAS is a huge undertaking that I'm unlikely to finish anytime soon.

**Comment by alyosha-tas** [comment]
The first frame after power on is shorter than the others, so it adds some difficulties, but I thought up a way to do it so I'll work on it in the next week or two.

**Comment by alyosha-tas** [comment]
@RetroEdit console reset is now enabled in master branch, if you can build from source please test your use case.

**Comment by RetroEdit** [comment]
No issues here.
