### ISSUE TITLE
TAStudio columns are odd with multi-GBA

### ISSUE THREAD

**Issue by RetroEdit** [alyosha-tas/GBAHawk#27]
When I press buttons in recording mode, the columns are mislabeled (the game processes the presses as expected). This seems likely to be a rendering bug caused by an extra `!` column to the left.

Also, whenever I click on the columns for player 2, it just visually fills the whole column with the column's letter instead of properly setting the button.

**Comment by alyosha-tas** [comment]
Having trouble reproducing this one, can you give any more info?

**Comment by RetroEdit** [comment]
Sure, these are some repro steps:

1) Open GBAHawk 2.1.0 (I started with a fresh extraction of the released file)
2) (I paused the emulator and set up the GBA firmware to be in the `Firmware` path)
3) The first time, I was playing Game & Watch Gallery 4, but this time I choose Donkey Kong Country.
4) I opened `Tools > Multi-disk Bundler` and choose `System`: `GBAL`, then chose DKC for the first entry and GBA BIOS as the second one and pressed `Save and Run` (relevant XML)
5) I opened `Tools > TAStudio` (image attached)

[GBAHawk_issue_000027.zip](https://github.com/alyosha-tas/GBAHawk/files/14289171/GBAHawk_issue_000027.zip)

I can compile it myself and look into it if you're still not able to reproduce.

**Comment by alyosha-tas** [comment]
The '!' is meant to be used for a yet to be implemented toggle for connecting / disconnecting the link cable, so it's supposed to be there. 

I can't reproduce the misaligned inputs though or other glitches.

**Comment by alyosha-tas** [comment]
Weird. I tried every combination of recording mode, virtual pad input, keyboard input I could think of for player 1 and 2 and never got such an error. Yeah please let me know if you come up with anything

**Comment by RetroEdit** [comment]
Hm, seems like this was probably fixed in intervening builds.
