### ISSUE TITLE
Core used is GBAHawk_Debug, regardless of choice?

### ISSUE THREAD

**Issue by RetroEdit** [alyosha-tas/GBAHawk#32]
Welcome to part 3 of my series: "minor header issues that may not be worth filing an issue for".

In 2.1.1, it seems like the core name is saved to a movie header as `GBAHawk_Debug` regardless of what core is selected.

As a further note, it seems like GBAHawk 2.1.1 uses `GBAHawk_Debug` regardless of what core is selected, so the issue is probably a bit more broad than movies.

**Comment by alyosha-tas** [comment]
I fixed this error and backported to 2.1.1
