### ISSUE TITLE
New visual bug in 2.1.x

### ISSUE THREAD

**Issue by RetroEdit** [alyosha-tas/GBAHawk#33]
This is how Shrek 2 is supposed to be when transitioning between the book screen and chapter screen (1/6 speed video from BizHawk 2.9.1, but I checked other emulators and real console, and this is more similar to how it's supposed to appear):

![Shrek_2_menu_mGBA](https://github.com/alyosha-tas/GBAHawk/assets/30182911/8e4f9a5d-8b18-44c0-867d-96feb99b34c2)

This is how it looks in GBAHawk 2.1.1:

![Shrek_2_menu_GBAHawk](https://github.com/alyosha-tas/GBAHawk/assets/30182911/ec522620-7967-44c9-9812-0de39c6f4b88)

This appears to be a regression between GBAHawk 2.0.0 and GBAHawk 2.1.0

**Comment by alyosha-tas** [comment]
Oh, good catch, I'll fix this in the coming days

**Comment by alyosha-tas** [comment]
Fixed and backported to 2.1.1
