### ISSUE TITLE
Coin Fall: Notes aren't held

### ISSUE THREAD

**Issue by fsvgm777** [alyosha-tas/GBAHawk#4]
In Coin Fall, the music notes aren't held and instead cut off way too early.

Here's a video showing what I mean: https://www.youtube.com/watch?v=SemXO50TaqQ (ignore the really low quality, I just uploaded the AVI straight to YouTube)

For comparison, here's how it's supposed to sound like: https://www.youtube.com/watch?v=avBgeBKQ8

**Comment by alyosha-tas** [comment]
Oh good catch. Was a simple audio bug. Fixed in re-released v1.5
