### ISSUE TITLE
Metroid Zero Mission Fails to Connect to Metroid Fusion

### ISSUE THREAD

**Issue by Danik2343** [alyosha-tas/GBAHawk#45]
![GBAHawk_RCVnghrNP0](https://github.com/user-attachments/assets/ae2eb672-b3a9-4d9a-9c77-7cff3b4be373)

**Comment by alyosha-tas** [comment]
Was this meant to be closed? Is it working?

**Comment by Danik2343** [comment]
It's working, second GBA with Fusion needs in Multi boot mode.
