### ISSUE TITLE
[Request] Keep old versions up

### ISSUE THREAD

**Issue by SamsaraTAS** [alyosha-tas/GBAHawk#6]
It came to my attention that every version prior to 1.5 has been removed, which makes TASVideos' judgement and verification process much more difficult. If sync stability were to have changed in 1.5, then all three of the GBAHawk submissions would have essentially become unplayable in their current forms.

I'd like to request that, going forward, releases should not be removed, barring some sort of catastrophic error. Ideally, 1.3 and 1.4 would be put back up as well for archival purposes, but as long as your submissions all sync on 1.5 then it isn't strictly necessary.

**Comment by alyosha-tas** [comment]
Yes I will keep versions up going forward from 1.5. Previous versions contained a critical emulation bug making them unsuitable for use.

All my submissions sync on 1.5, so that version can be used in the submission / publication details.

Apologies for the churn.
